- name: ansible to install pymysql and cryptography
  ansible.builtin.pip:
    name:
    - PyMySQL
    - cryptography
    executable: pip3.9
    
- name: installing mysql server
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: starting and enable services
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: connecting to user to check if already password set or not
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_password }}"
    login_host: "{{ login_host }}"
  ignore_errors: true
  register: mysql_info

- name: password reset if it is not set
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_password }}"
  when: mysql_info.failed is true





